version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mine-lambda"
s3_bucket = "mine-lambda"
s3_prefix = "mine-lambda"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
